version: "3"

services:
  db:
    image: postgres # Use a specific version, e.g., postgres:16
    container_name: elysia-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data across container restarts
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432

volumes:
  pgdata:
